### ISSUE TITLE
フルカラーLEDを制御

### ISSUE THREAD

**Issue by greenlaver** [jphacks/KB_1808#2]
# フルカラーLEDを制御する
フルカラーシリアルLEDテープをESP32から制御する。

既知の問題として、**Adafruitのライブラリをそのまま利用すると、多数のLEDアレイに対して制御が不安定になるバグ**が存在するので注意。

以下各種情報

https://www.switch-science.com/catalog/1399/

**Comment by kanon-k4** [comment]
http://mag.switch-science.com/2013/04/01/fullcolor_serialled_tape/

**Comment by kanon-k4** [comment]
IDE自体でライブラリを導入に、上記リンクのサンプルを適用でLED点灯しました。
この後、制御の流れを確認します。
